// pulled from the Umamusume Wiki, automatically generated.
// DO NOT EDIT MANUALLY.
export const OFFICIAL_CHARACTER_BIRTHDAYS = [
  { name: "Agnes Digital", birthday: "05-15" },
  { name: "Agnes Tachyon", birthday: "04-13" },
  { name: "Air Groove", birthday: "04-06" },
  { name: "Air Shakur", birthday: "02-26" },
  { name: "Bamboo Memory", birthday: "05-14" },
  { name: "Biko Pegasus", birthday: "02-08" },
  { name: "Biwa Hayahide", birthday: "03-10" },
  { name: "Curren Chan", birthday: "03-31" },
  { name: "Daitaku Helios", birthday: "04-10" },
  { name: "Daiwa Scarlet", birthday: "05-13" },
  { name: "Eishin Flash", birthday: "03-27" },
  { name: "El Condor Pasa", birthday: "03-17" },
  { name: "Fine Motion", birthday: "01-27" },
  { name: "Fuji Kiseki", birthday: "04-15" },
  { name: "Gold City", birthday: "04-16" },
  { name: "Gold Ship", birthday: "03-06" },
  { name: "Grass Wonder", birthday: "02-18" },
  { name: "Haru Urara", birthday: "02-27" },
  { name: "Hishi Akebono", birthday: "02-27" },
  { name: "Hishi Amazon", birthday: "03-26" },
  { name: "Ikuno Dictus", birthday: "04-16" },
  { name: "Ines Fujin", birthday: "04-10" },
  { name: "Kawakami Princess", birthday: "06-05" },
  { name: "King Halo", birthday: "04-28" },
  { name: "Kitasan Black", birthday: "03-10" },
  { name: "Manhattan Cafe", birthday: "03-05" },
  { name: "Maruzensky", birthday: "05-19" },
  { name: "Marvelous Sunday", birthday: "05-31" },
  { name: "Matikane Fukukitaru", birthday: "05-22" },
  { name: "Matikane Tannhauser", birthday: "05-07" },
  { name: "Mayano Top Gun", birthday: "03-24" },
  { name: "Meisho Doto", birthday: "03-25" },
  { name: "Mejiro Ardan", birthday: "03-28" },
  { name: "Mejiro Dober", birthday: "05-06" },
  { name: "Mejiro McQueen", birthday: "04-03" },
  { name: "Mejiro Palmer", birthday: "03-21" },
  { name: "Mejiro Ryan", birthday: "04-11" },
  { name: "Mihono Bourbon", birthday: "04-25" },
  { name: "Nakayama Festa", birthday: "04-05" },
  { name: "Narita Brian", birthday: "05-03" },
  { name: "Narita Taishin", birthday: "06-10" },
  { name: "Nice Nature", birthday: "04-16" },
  { name: "Nishino Flower", birthday: "04-19" },
  { name: "Oguri Cap", birthday: "03-27" },
  { name: "Rice Shower", birthday: "03-05" },
  { name: "Sakura Bakushin O", birthday: "04-14" },
  { name: "Sakura Chiyono O", birthday: "02-19" },
  { name: "Satono Diamond", birthday: "01-30" },
  { name: "Seeking the Pearl", birthday: "04-16" },
  { name: "Seiun Sky", birthday: "04-26" },
  { name: "Shinko Windy", birthday: "04-14" },
  { name: "Silence Suzuka", birthday: "05-01" },
  { name: "Sirius Symboli", birthday: "03-26" },
  { name: "Smart Falcon", birthday: "04-04" },
  { name: "Special Week", birthday: "05-02" },
  { name: "Super Creek", birthday: "05-27" },
  { name: "Sweep Tosho", birthday: "05-09" },
  { name: "Symboli Rudolf", birthday: "03-13" },
  { name: "T.M. Opera O", birthday: "03-13" },
  { name: "Taiki Shuttle", birthday: "03-23" },
  { name: "Tamamo Cross", birthday: "05-23" },
  { name: "Tokai Teio", birthday: "04-20" },
  { name: "Tosen Jordan", birthday: "02-04" },
  { name: "Twin Turbo", birthday: "04-13" },
  { name: "Vodka", birthday: "04-04" },
  { name: "Winning Ticket", birthday: "03-21" },
  { name: "Yaeno Muteki", birthday: "04-11" },
  { name: "Yukino Bijin", birthday: "03-10" },
  { name: "Zenno Rob Roy", birthday: "03-27" },
] as const;